name: Labeler

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@3de87da19416edc45c90cd89e7a4ea922a3aae5a # v4.1.0
        with:
          skip-delete: true